before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: NwKg22ARKgzPksBRkNw8NKpIWVSw92olX/MqyxHsoI6PERPrtv7AZib0sOZ8G6xl5QQmq0V+cmevM7KddAMFloKu+zYQxs+w/Zk4VVcAm0l7NhmB19vK6eaxsWikY9D65rK32G7bSUWa2Iz7x9EKFx7crpyuuPEuEHfaCScnydmnvvz6crqp4CVyCXtuhYaMMbVqdYQRa2/M6rL60VLdGwnL6ZYhV/GTPScEn46DmWtM0ZODVYibQlfufqq30cQy17Cz794FEyDrjakpghmz3W7nfS3q3XHMUBDFfyaKvdMVJMv3Zc1Xcb4RSQnZN8luYnjAbTmLwkIL/dXXUTkxHwr0yKQxF5bFM3hmz2wWvMS0AG4+ZT8rJlwNmsgjGrqTp+xqFbVDBKvrlMgSlx3WGoD9w9Mrej4A85lyiDuyHGIkwVeOQslcD5y4DNu8/N1KaNCfSLThEUqetOxGn/jPq2OZZLZhT49SQ6Hcb9rtiPyaJgoUeulVqqDG8XbPLyhGDL0mYyqBTflxpB4WA+1cFQpdWTi68SYVceTnXwHtMVofQktGAUghptpfyfMDjAG0VKQSY8CK8F/c0iDzEOUDEDfVkBHiAegqTvhRnpu+JPUP3V9stXuM8nqUXCUHgCYUKwgrAmuxpzQwHzEphMBIjHZ1IYUnGBmETztbZ1bUk1c= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
